services:
  app:
    build: ./app
    env_file: ./.env
    environment:
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    stdin_open: true
    tty: true
    networks:
      - dokploy-network
    volumes:
      - /root/mcgl:/app/.source
    ports:
      - "80"
networks:
  dokploy-network:
    external: true
