services:
  mongodb:
    image: mongo
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    volumes:
      - db:/data/db
    networks:
      - dokploy-network
  app:
    depends_on:
      - mongodb
    build: ./app
    restart: unless-stopped
    env_file: ./.env
    environment:
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    stdin_open: true
    tty: true
    networks:
      - dokploy-network
    volumes:
      - /root/mcgl:/app/.source
volumes:
  db:
networks:
  dokploy-network:
    external: true
